project:
  type: website
  output-dir: docs
  
website:
  title: "Conor O'Driscoll"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/conorodriscollx
      - icon: github
        href: https://github.com/conor-o-driscoll/personal-website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Conor O'Driscoll"

format:
  html:
    theme: cerulean
    toc: true

editor: source

